from __future__ import annotations

from typing import Protocol

from irlds.models import TelemetryFrame


class TelemetrySource(Protocol):
    def poll(self) -> TelemetryFrame | None: ...
    def sector_boundaries(self) -> list[float] | None: ...
    def session_signature(self) -> str: ...
    def close(self) -> None: ...
